### ISSUE TITLE
ENOENT: no such file or directory with npx, works with java

### ISSUE THREAD

**Issue by crinitic** [google/closure-compiler-npm#108] opened 2018-09-16 17:56 UTC
I am trying to compile my client js files with the google closure compiler, and it works well with java:
`java -jar node_modules/google-closure-compiler/compiler.jar --js=public/**.js`

However, if I try to do the same through node or npx (as documented here), I always get the same error:
`npx google-closure-compiler --js=public/**.js`
`node .\node_modules\google-closure-compiler\cli.js --js=public/**.js`

Both return the same error
```
{ [Error: ENOENT: no such file or directory, open 'D:\myfolder\public\**.js']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\myfolder\\public\\**.js' }
TypeError: Cannot read property 'path' of undefined
    at Ird (D:\myfolder\node_modules\google-closure-compiler\jscomp.js:5364:88)
    at Drd (D:\myfolder\node_modules\google-closure-compiler\jscomp.js:7747:257)
...
```
The path `D:\\myfolder\\public\\` is correct

It would be very handy if I could compile all files without installing JRE.

**Comment by ChadKillingsworth** [comment] 2018-09-19 01:12
I'll see about testing this on Windows since that seems to be the issue here.

FYI if you specify the `--platform=javascript`, then no JRE is required. Until a native image is available on windows, that's the best option.

**Comment by ChadKillingsworth** [comment] 2018-09-29 10:47
A reworked cli script was published with v20180910.1.0. Can you test this again and see if it's still an issue?

**Comment by crinitic** [comment] 2018-09-29 18:53
With 20180910.1.0, I get a different error:
```
npx google-closure-compiler --js=client/**.js
{ Error: Cannot find module '../../jscomp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\myproject\node_modules\google-closure-compiler\lib\node\closure-compiler-js.js:27:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
```

I also tried to `npm install jscomp`, but it didn't help

**Comment by ChadKillingsworth** [comment] 2018-10-01 16:11
I cannot reproduce the exact issue you have above.

However, it does look like the JS version does not properly handle wildcards. I get a different error when I try that.

**Comment by ChadKillingsworth** [comment] 2018-10-01 16:16
Moving to the main compiler repo: https://github.com/google/closure-compiler/issues/3096

**Closed by ChadKillingsworth** 2018-10-01 16:16 UTC
