### ISSUE TITLE
native-image version of compiler claims 1970 is the latest meaningful value to use for browser_featureset_year

### ISSUE THREAD

**Issue by AshleyScirra** [google/closure-compiler-npm#173] opened 2020-05-16 17:51 UTC
I tried setting `browser_featureset_year 2020` in the command line, e.g.:

`npx google-closure-compiler --js in.js --js_output_file out.js --browser_featureset_year 2020`

This logs the message:
`--browser_featureset_year=1970 is the latest meaningful value to use`

Clearly this is wrong - browsers didn't exist in 1970! It's probably parsing the value incorrectly.

**Comment by rishipal** [comment] 2020-05-16 22:21
This can be happening only if the current year obtained from LocalDataTime is 1970, which indicates that maybe your system time clock is set to that year. Can you confirm your system clock year?

Fyi, the code responsible for causing this is:
```
int currentYear = LocalDateTime.now(ZoneId.systemDefault()).getYear();
    if (inputYear > currentYear) {
      throw new FlagUsageException(
          SimpleFormat.format(
              "--browser_featureset_year=%d is the latest meaningful value to use", currentYear));
```

**Comment by AshleyScirra** [comment] 2020-05-17 11:40
My system clock is set correctly - at time of writing, it says 17th May 2020.

**Comment by rishipal** [comment] 2020-05-18 18:46
On which version of google-closure-compiler are you seeing this problem? 
I haven't been able to reproduce on the latest https://www.npmjs.com/package/google-closure-compiler

**Comment by AshleyScirra** [comment] 2020-05-18 18:51
`npx google-closure-compiler --version` prints:

```
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20200504
Built on: 2020-05-06 19:27
```

**Comment by blickly** [comment] 2020-05-21 21:36
My initial guess would be that it has something to do with one of the alternative platforms.

Can you try with `--platform=java` (the configuration that we use most at google) to see if it works in that mode?

If so, it may be an issue with graal (for the native binary version) or j2cl/gwt (for the JavaScript version).

**Comment by AshleyScirra** [comment] 2020-05-22 11:11
If I run `npx google-closure-compiler --js in.js --js_output_file out.js --browser_featureset_year 2020 --platform=java`, there is no error about `browser_featureset_year`. However it doesn't produce an output file either. I don't have Java installed though, I guess I need it for that option?

**Comment by AshleyScirra** [comment] 2020-05-26 13:54
I installed Java for some other testing so I gave this a spin with Java installed.

`npx google-closure-compiler --js in.js --js_output_file out.js --browser_featureset_year 2020`
Result: `--browser_featureset_year=1970 is the latest meaningful value to use`

`npx google-closure-compiler --platform=java --js in.js --js_output_file out.js --browser_featureset_year 2020`
Result: `WARNING - [JSC_UNKNOWN_DEFINE_WARNING] unknown @define variable goog.FEATURESET_YEAR`

`java -jar closure-compiler.jar --js in.js --js_output_file out.js --browser_featureset_year 2020`
Result: `WARNING - [JSC_UNKNOWN_DEFINE_WARNING] unknown @define variable goog.FEATURESET_YEAR`

Hmm... is the option just broken?

**Comment by blickly** [comment] 2020-05-26 18:29
Well, that is a very different error message, which makes me think that there is some bug in one of the tools that we use to transpile the non-java versions. (I think that the default version when running without the --platform flag is a native versions compiled with graal).  https://github.com/oracle/graal/issues/1374 looks somewhat similar, but is already fixed.

From the `--platform=java` output, it looks like the JS code defining `goog.FEATURESET_YEAR` is missing. Are you perhaps using an old version of closure-library from before `goog.FEATURESET_YEAR` was added in https://github.com/google/closure-library/commit/9234c1abe30ca42104853254e478bdb2496ef7e7 ?

**Comment by blickly** [comment] 2020-05-26 18:35
Created Google internal issue http://b/157485632

**Comment by blickly** [comment] 2020-05-26 18:38
I've renamed this bug to be specific to the the original issue without the `--platform=java` flag.

If using a more recent version of closure-library doesn't fix the issue `--platform=java` issue, could you file a new issue on https://github.com/google/closure-compiler/issues/new/choose
?

**Comment by shicks** [comment] 2020-05-26 19:59
FWIW, Closure Library maintainers are interested in cutting the dependencies between the library and the compiler so that each can be meaningfully used independent of the other.  We should look into finding a way to make FEATURESET_YEAR usable without Closure Library.

**Comment by blickly** [comment] 2020-05-27 00:32
Note also, that on my OS X machine, I wasn't able to reproduce this issue with the native-image version of the compiler.

**Comment by blickly** [comment] 2020-05-27 00:56
Can you tell us which platform you are running on (windows, linux, os x, etc.)?

**Comment by AshleyScirra** [comment] 2020-05-27 10:29
My previous comment was based on running Closure Compiler v20200517 on Windows 10 x64.

**Comment by brad4d** [comment] 2020-05-28 00:02
does `--platform=js` give the same error as `--platform=java`?

@ChadKillingsworth do you know what version of Graal we're using here?
Maybe it still has the issue oracle/graal#1374 ?

**Comment by concavelenz** [comment] 2020-06-11 18:05
I expect this to be fixed by: https://github.com/google/closure-compiler-npm/pull/174
Chad can you confirm this?

**Comment by ChadKillingsworth** [comment] 2020-06-21 12:43
I _think_ it will be. At least it looks like the version of Graal is newer than when that fix was merged.

**Comment by lauraharker** [comment] 2020-06-24 20:35
This should also have been fixed by Rishi's https://github.com/google/closure-compiler/commit/041dc07d025b64fcf0239359bc732dd78c3d2e75, once that's released.

**Comment by rishipal** [comment] 2020-07-20 23:45
Is this still failing on Win10 x64?

**Closed** 2020-07-20 23:45 UTC
Labels: internal-issue-created, triage-done
