### ISSUE TITLE
`google-closure-compiler-linux` throwing Java exceptions.

### ISSUE THREAD

**Issue by robertfirek** [google/closure-compiler-npm#234] opened 2022-04-08 13:50 UTC
Executing the following command:
```
npx google-closure-compiler target/resources/main/js/es6-bundle.js > target/resources/main/js/es5-bundle.js --language_in=ECMASCRIPT_2017 --language_out=ECMASCRIPT5 --compilation_level=SIMPLE_OPTIMIZATIONS --rewrite_polyfills=true --warning_level=QUIET --jscomp_off=checkVars --create_source_map target/resources/main/js/es5-bundle.js.map
```
produces the following error statement:
```
java.util.zip.ZipException: invalid entry CRC (expected 0x4e1f14a4 but got 0xb1e0eb5b)
        at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:410)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:199)
        at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:143)
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:121)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.getBuiltinExterns(AbstractCommandLineRunner.java:481)
        at com.google.javascript.jscomp.CommandLineRunner.createExterns(CommandLineRunner.java:2073)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1168)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:532)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2231)
```

I confirmed that the native compiler is executed in this case (from `google-closure-compiler-linux` package). Force refresh and reinstallation of modules doesn't fix the problem.

**Versions:**
"20220202.0.0", "20220405.0.0"

**Operating system:**
Linux 5.10.105-1-MANJARO x86_64

**Java version:**
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)

**Comment by brad4d** [comment] 2022-04-11 23:07
@ChadKillingsworth does this look like there's something wrong with the Graal build to you?

**Comment by ChadKillingsworth** [comment] 2022-04-11 23:24
I'm not sure. It could be.

**Comment by brad4d** [comment] 2022-04-12 15:38
When I use `npx google-closure-compiler`, how can I tell whether it is using the java version or the Graal binary?

**Comment by ChadKillingsworth** [comment] 2022-04-12 18:33
Add the `--platform=native` flag to the command to guarantee it.

If we think it's Graal, we can use the nightly builds to find out when it was first introduced:

`npx google-closure-compiler@20220412.0.0-nightly --platform=native...`

https://www.npmjs.com/package/google-closure-compiler

**Comment by noppa** [comment] 2022-04-16 12:41
I created a minimal reproducible example of this using Docker: [noppa/google-closure-compiler-npm-issue234-mre](https://github.com/noppa/google-closure-compiler-npm-issue234-mre)

Everything works fine with Ubuntu as the base image, but fails with Arch Linux

**Comment by ChadKillingsworth** [comment] 2022-04-16 16:04
It's going to be challenging to figure out what is causing this. This feels less like an issue with the binary and more that a system library of some sort is missing.

**Comment by noppa** [comment] 2022-04-16 22:40
I tested an old version (2022-01-01) of google-closure-compiler and it still errored. I'm pretty sure I've successfully used a later version of the library on Arch so, like @ChadKillingsworth suspected, it's probably not an issue in a version of google-closure-compiler but rather the platform.

So [I did a little experiment](https://github.com/noppa/google-closure-compiler-npm-issue234-mre/blob/main/test-each-version.sh) with git bisect that uses [Arch Linux Archive](https://wiki.archlinux.org/title/Arch_Linux_Archive) to install packages from an archive of a specific date between today and 2022-03-01.

Turns out 2022-03-30 is the first date whose archives reproduce this error. Installing packages from 03-29 first and then upgrading to archives of 03-30 shows that the changed packages are (drum roll... :drum:)

```
Package (2)      Old Version  New Version  Net Change  Download Size

core/libarchive  3.6.0-1      3.6.0-2        0.00 MiB       0.50 MiB
core/zlib        1:1.2.11-5   1:1.2.12-1     0.00 MiB       0.09 MiB
```
Given that the error message is a ZipException, this seems like pretty damning evidence that one of these two package updates is the culprit.

Zlib changelog is [here](https://www.zlib.net/ChangeLog.txt) and the libarchive release is [here](https://github.com/libarchive/libarchive/releases/tag/v3.6.0).

**Comment by noppa** [comment] 2022-04-16 23:02
Yeah, looks like it's probably https://github.com/madler/zlib/issues/426

**Comment by ChadKillingsworth** [comment] 2022-04-17 12:02
It looks more related to https://github.com/madler/zlib/issues/613.

Nice find btw. Since this is clearly not closure-compiler at this point, I'm going to close the issue.

**Closed by ChadKillingsworth** 2022-04-17 12:02 UTC
Labels: help wanted

**Comment by noppa** [comment] 2022-04-17 13:52
If any of the Arch users here want to get things working right away without waiting for the next release of zlib, you can manually rebuild the package with [this zlib patch](https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2) applied to it:
```sh
git clone -b packages/zlib --depth 1 https://github.com/archlinux/svntogit-packages.git
cd svntogit-packages/trunk
curl -O https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2.patch
curl -o- https://gist.githubusercontent.com/noppa/cb606d86b458ee30b7da8cd73c143a18/raw/6ac6e3faf12d06fc85bab105ade59c55214a76c0/zlib-PKGBUILD.patch | git apply
gpg --recv-key 783FCD8E58BCAFBA
makepkg --clean --syncdeps --rmdeps
sudo pacman -U zlib-1:1.2.12-1-x86_64.pkg.tar.zst
```
After running these, google-closure-compiler should work normally again.

**Comment by robertfirek** [comment] 2022-04-19 14:21
Thank you all for your help. 

It is a problem with `zlib` library. I installed the old version of the library (`1.2.11-5`) and the problem disappeared. I think I will wait for the next release of `zlib`.
